spring: 
  profile: 
    active:  
    - dev

---
server: 
  port: 7003 # 注册中心占用7003端口，冒号后面必须有空格

spring: 
  profiles: dev
  application:
    name: config-eureka-7003
    
eureka: 
  instance: 
    hostname: eureka7003.com
  client: 
    register-with-eureka: false # 当前的eureka-server自己不注册进服务列表中
    fetch-registry: false # 不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  
---
server: 
  port: 7003 # 注册中心占用7003端口，冒号后面必须有空格

spring: 
  profiles: test
  application:
    name: config-eureka-7003
    
eureka: 
  instance: 
    hostname: eureka7003.com
  client: 
    register-with-eureka: false # 当前的eureka-server自己不注册进服务列表中
    fetch-registry: false # 不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/